//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pj {

public enum pj_qos_flag {
  PJ_QOS_PARAM_HAS_DSCP = 1,
  PJ_QOS_PARAM_HAS_SO_PRIO = 2,
  PJ_QOS_PARAM_HAS_WMM = 4
}

}
