//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pj {

public enum pjmedia_file_writer_option {
  PJMEDIA_FILE_WRITE_PCM = 0,
  PJMEDIA_FILE_WRITE_ALAW = 1,
  PJMEDIA_FILE_WRITE_ULAW = 2
}

}
