//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pj {

public enum pjsua_call_flag {
  PJSUA_CALL_UNHOLD = 1,
  PJSUA_CALL_UPDATE_CONTACT = 2,
  PJSUA_CALL_INCLUDE_DISABLED_MEDIA = 4,
  PJSUA_CALL_NO_SDP_OFFER = 8
}

}
